"""End-to-end CI pipeline authoring — the single entry point for a real run.

``run_ci_pipeline`` chains Discover -> Generate -> Validate -> deliver secrets
(via a ``SecretsProvider``) -> open a real PR. Dependencies are injectable so the
whole chain is unit-testable offline (mock repo, stub discover/generate). This is
the deterministic path the direct ``/ci`` endpoint calls — no LLM in the loop, so
real secret values are handled here, never sent to a model.
"""
from __future__ import annotations

import re
from typing import Optional

from .github_client import get_repo, open_pr, parse_repo_full_name
from .secrets_provider import GitHubActionsSecrets, SecretsProvider
from .tools.tools import (
    DiscoverProject,
    GenerateGitHubActionsWorkflow,
    ValidateWorkflow,
)

# UI (tool, field-label) -> the GitHub Actions secret name the workflow expects.
# Names here line up with the ${{ secrets.* }} references the generator emits.
SECRET_MAP = {
    ("SonarQube", "Host URL"): "SONAR_HOST_URL",
    ("SonarQube", "Token"): "SONAR_TOKEN",
    ("SonarCloud", "Organization"): "SONAR_ORG",
    ("SonarCloud", "Token"): "SONAR_TOKEN",
    ("Fortify SSC", "SSC URL"): "FORTIFY_SSC_URL",
    ("Fortify SSC", "Auth token"): "FORTIFY_TOKEN",
    ("Sonatype Nexus IQ", "IQ Server URL"): "SONATYPE_IQ_URL",
    ("Sonatype Nexus IQ", "Auth token"): "SONATYPE_TOKEN",
    ("Snyk", "API token"): "SNYK_TOKEN",
    ("Wiz", "Client ID"): "WIZ_CLIENT_ID",
    ("Wiz", "Client secret"): "WIZ_CLIENT_SECRET",
    ("Nexus", "Repository URL"): "NEXUS_REPO_URL",
    ("Nexus", "Username"): "NEXUS_USERNAME",
    ("Nexus", "Password"): "NEXUS_PASSWORD",
    ("JFrog Artifactory", "Base URL"): "ARTIFACTORY_URL",
    ("JFrog Artifactory", "Access token"): "ARTIFACTORY_TOKEN",
    ("GitHub Packages", "Personal access token"): "REGISTRY_TOKEN",
    ("Azure ACR", "Login server"): "REGISTRY_URL",
    ("Azure ACR", "Username"): "REGISTRY_USERNAME",
    ("Azure ACR", "Password"): "REGISTRY_PASSWORD",
    ("Docker Hub", "Username"): "REGISTRY_USERNAME",
    ("Docker Hub", "Access token"): "REGISTRY_TOKEN",
    ("GHCR", "PAT"): "REGISTRY_TOKEN",
    ("AWS ECR", "Region"): "AWS_REGION",
    ("AWS ECR", "Access key ID"): "AWS_ACCESS_KEY_ID",
    ("AWS ECR", "Secret access key"): "AWS_SECRET_ACCESS_KEY",
    ("Dynatrace", "Environment ID"): "DYNATRACE_ENVIRONMENT_ID",
    ("Dynatrace", "API token"): "DYNATRACE_API_TOKEN",
    ("Splunk", "HEC URL"): "SPLUNK_HEC_URL",
    ("Splunk", "HEC token"): "SPLUNK_HEC_TOKEN",
}


def _generic_name(prefix: str, label: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", f"{prefix}_{label}").strip("_").upper()


def to_actions_secrets(selected_tools: dict) -> dict:
    """Flatten the UI's {capability: {tool, <label>: <value>}} into
    {ACTIONS_SECRET_NAME: value}. Masked placeholders and blanks are dropped, so
    only real values ever become secrets."""
    out: dict[str, str] = {}
    for capability, entry in (selected_tools or {}).items():
        if not isinstance(entry, dict):
            continue
        tool = entry.get("tool")
        for label, value in entry.items():
            if label == "tool" or value in (None, "", "[provided via UI]"):
                continue
            name = SECRET_MAP.get((tool, label)) or _generic_name(tool or capability, label)
            out[name] = value
    return out


def _default_project_name(repo_url: str) -> str:
    tail = parse_repo_full_name(repo_url).split("/")[-1]
    cleaned = re.sub(r"[^A-Za-z0-9]+", " ", tail).title().replace(" ", "")
    return cleaned or "App"


def _pr_body(name: str, secret_results: list[dict]) -> str:
    set_names = [r["name"] for r in secret_results if r.get("status") == "set"]
    lines = [
        f"Automated CI pipeline for **{name}**, generated by NetcoreCIAgent.",
        "",
        "## What this adds",
        "- `.github/workflows/ci-pipeline.yml` — build, test, SonarQube, "
        "SAST/SCA/DAST, container build + SBOM + scan, Nexus, Helm, monitoring.",
        "",
        "## Secrets configured (values not shown)",
        (("- " + "\n- ".join(set_names)) if set_names else "- (none set this run)"),
        "",
        "> Review and merge when ready — this PR is **not** auto-merged.",
    ]
    return "\n".join(lines)


def run_ci_pipeline(
    *,
    repo_url: str,
    github_token: str,
    project_name: Optional[str] = None,
    options: Optional[dict] = None,
    pipeline_secrets: Optional[dict] = None,
    repo=None,
    discover_tool=None,
    generate_tool=None,
    validate_tool=None,
    secrets_provider: Optional[SecretsProvider] = None,
) -> dict:
    """Run the real CI flow. Returns a structured result incl. the live PR URL.

    Injectables (``repo``, ``*_tool``, ``secrets_provider``) let tests run the
    whole chain with mocks and no network.
    """
    options = options or {}

    # 1) Discover
    disc = (discover_tool or DiscoverProject()).run(
        repo_url=repo_url, branch=options.get("branch", "main")
    )
    if disc.get("status") == "error":
        return {"status": "error", "stage": "discover", "error": disc.get("error")}

    framework = disc.get("target_framework") or ".NET 8"
    name = project_name or _default_project_name(repo_url)

    # 2) Generate
    gen = (generate_tool or GenerateGitHubActionsWorkflow()).run(
        project_name=name,
        target_framework=framework,
        build_tool=disc.get("build_tool") or ".NET CLI",
        include_dast=options.get("include_dast", True),
        enable_docker_build=disc.get("docker_support", True),
        enable_helm_update=disc.get("helm_support", True),
    )
    if gen.get("status") == "error":
        return {"status": "error", "stage": "generate", "error": gen.get("error")}
    workflow_yaml = gen["workflow_yaml"]
    workflow_path = gen["workflow_path"]

    # 3) Validate (fail fast rather than open a broken PR)
    val = (validate_tool or ValidateWorkflow()).run(
        workflow_yaml=workflow_yaml, workflow_name=f"{name}-ci"
    )
    if not val.get("valid"):
        return {"status": "validation_failed", "stage": "validate", "validation": val}

    # 4) Deliver secrets (Model A — GitHub Actions secrets)
    repo = repo or get_repo(github_token, parse_repo_full_name(repo_url))
    provider = secrets_provider or GitHubActionsSecrets(repo)
    secret_results = (
        provider.set_many(pipeline_secrets or {})
        if options.get("set_secrets", True)
        else []
    )

    # 5) Open a real PR (never merge)
    pr = None
    if options.get("open_pr", True):
        branch = options.get("pr_branch") or f"ci/netcore-{name.lower()}"
        pr = open_pr(
            repo,
            workflow_path=workflow_path,
            workflow_yaml=workflow_yaml,
            branch=branch,
            title=f"Add CI pipeline for {name}",
            body=_pr_body(name, secret_results),
        )

    result = {
        "status": "opened" if pr else "generated",
        "repo": parse_repo_full_name(repo_url),
        "discovery": {
            "target_framework": framework,
            "existing_ci_pipeline": disc.get("existing_ci_pipeline"),
        },
        "validation": {"valid": True},
        "secrets": secret_results,
        "workflow_path": workflow_path,
        "pr": pr,
    }
    failed = [r["name"] for r in secret_results if r.get("status") == "failed"]
    if failed:
        result["warnings"] = [
            "Could not set these Actions secrets: " + ", ".join(failed) +
            " — the GitHub token is missing the 'Secrets' (read/write) permission. "
            "The PR was still opened; add the permission (or set the secrets manually) "
            "and the pipeline will pick them up."
        ]
    return result
